server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://47.115.214.50:3306/yshs_tect?useSSL=false&serverTimezone=UTC
    username: yshs_tect
    password: ZtpXXsXpzSxTjBWs
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.yunshan.tech.model

file:
  upload-dir: ./uploads

